# Generated by Django 2.2.5 on 2019-09-27 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('sick_leave', models.FloatField(default=7)),
                ('annual_leave', models.FloatField(default=12)),
                ('compensation_leave', models.FloatField(default=0)),
                ('fcm_token', models.CharField(blank=True, max_length=255)),
                ('leave_issuer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='leave_issuer', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
