# Generated by Django 2.2.5 on 2019-09-30 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanergy_leave', '0003_auto_20190930_1654'),
        ('users', '0002_auto_20190927_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='annual_leave',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='compensation_leave',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fcm_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='leave_issuer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sick_leave',
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user_department', to='sanergy_leave.Department'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_employee',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_staff',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
