# Generated by Django 2.2.5 on 2019-09-27 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('empLeave_req_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_fullname', models.CharField(max_length=60)),
                ('Leave_Type', models.CharField(help_text='Which type of leave are you taking', max_length=10)),
                ('Begin_Date', models.DateField(help_text='Leave begin date')),
                ('End_Date', models.DateField(help_text='Leave end date')),
                ('Requested_Days', models.PositiveIntegerField(default=0, help_text='Total no of requested leave days')),
                ('Comments', models.CharField(max_length=500, null=True)),
                ('emp_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
    ]
