# Generated by Django 2.2.5 on 2019-09-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanergy_leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='Comments',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='Leave_Type',
            field=models.CharField(max_length=300),
        ),
    ]
