# Generated by Django 2.2.5 on 2019-09-30 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sanergy_leave', '0002_auto_20190930_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employment_Terms', models.CharField(choices=[('PERMANENT', 'Permanent'), ('PARTTIME', 'Parttime'), ('PROBATIONARY', 'Probationary')], default='probationary', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Leave_Types', models.CharField(choices=[('EXPECTANCY', 'Expectancy'), ('ANNUAL_LEAVE', 'annual'), ('MILITARY_LEAVE', 'military'), ('EDUCATION_LEAVE', 'education')], default='annual', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('EMPLOYEE', 'employee'), ('MANAGER', 'manager')], default='employee', max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='empLeave_req_id',
            new_name='leave_id',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='emp_fullname',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='emp_id',
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_issuer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_issuer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leave',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leave',
            name='Comments',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='Leave_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanergy_leave.LeaveTypes'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='Requested_Days',
            field=models.PositiveIntegerField(default=5, help_text='Total no of requested leave days'),
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='Emergency Notice', max_length=100)),
                ('message', models.TextField()),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(default='Service', max_length=30)),
                ('head_of_department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='head_of_department', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
