# Generated by Django 2.2.5 on 2019-09-30 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanergy_leave', '0003_auto_20190930_1654'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmploymentTerms',
            new_name='EmploymentTerm',
        ),
        migrations.RenameModel(
            old_name='LeaveTypes',
            new_name='LeaveType',
        ),
    ]
